### ISSUE TITLE
Which will show your task’s time when you started and when you finished. (Calendar)

### ISSUE THREAD

**Issue by ShettaKeval20** [ShettaKeval20/AchieveIt#8]
As a user, I can view my task calendar with dates and times, allowing me to track when I completed my work, thereby enabling self-improvement based on this information.

**Comment by riyagoswami1005** [comment]
In calendar feature the date task is accomplished successfully .

**Comment by riyagoswami1005** [comment]
But in calendar feature the time task is cancelled.
